### ISSUE TITLE
partner focused landing page documenting setup

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/uHTTP-lib#20]
Getting uHTTP to work for your project requires:

- you run one or more of the simple hoprd entry-exit-app combi sets (https://app.zenhub.com/workspaces/eng-products-65fa946b29625b0035ad9733/issues/gh/hoprnet/hopr-network-dashboard/49)
- you let hopr register your entry - exit nodes associated with your client id (https://app.zenhub.com/workspaces/eng-products-65fa946b29625b0035ad9733/issues/gh/hoprnet/hopr-network-dashboard/48)

This process should be documented on a public non linked website that we can let partners access.

**Comment by mjadach-iv** [comment]
https://github.com/hoprnet/uHTTP-lib/blob/este/fixes/ROUTING.md

**Comment by mjadach-iv** [comment]
Will do domumentation instead of that

**Comment by esterlus** [comment]
see https://github.com/hoprnet/uHTTP-lib/blob/main/ONBOARDING.md
