### ISSUE TITLE
one-off docker compose to setup minimal hoprd node alongside uHTTP exit application

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/uHTTP-lib#21]
Projects should be able to easily spin up their own nodes to ensure request/response latency is minimal and to have full control over the exit application.

- have a docker compose setup that spins up a hoprd node (works as entry and exit node) and a uHTTP exit application
- projects should be able to run multiple of those with minimal setup adjustments

**Comment by esterlus** [comment]
see https://github.com/hoprnet/uhttp-docker
